//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmSTools.Resources.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PmSTools.Resources.Languages.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MainPage_MainPage_PmS_Main_Tools {
            get {
                return ResourceManager.GetString("MainPage_MainPage_PmS_Main_Tools", resourceCulture);
            }
        }
        
        internal static string NotAvailableYet {
            get {
                return ResourceManager.GetString("NotAvailableYet", resourceCulture);
            }
        }
        
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        internal static string PrefixsText {
            get {
                return ResourceManager.GetString("PrefixsText", resourceCulture);
            }
        }
        
        internal static string SavedText {
            get {
                return ResourceManager.GetString("SavedText", resourceCulture);
            }
        }
        
        internal static string NoPrefixesText {
            get {
                return ResourceManager.GetString("NoPrefixesText", resourceCulture);
            }
        }
        
        internal static string LastCodesText {
            get {
                return ResourceManager.GetString("LastCodesText", resourceCulture);
            }
        }
        
        internal static string CameraText {
            get {
                return ResourceManager.GetString("CameraText", resourceCulture);
            }
        }
        
        internal static string FileText {
            get {
                return ResourceManager.GetString("FileText", resourceCulture);
            }
        }
        
        internal static string Code2BarcodeText {
            get {
                return ResourceManager.GetString("Code2BarcodeText", resourceCulture);
            }
        }
        
        internal static string FindPlaceText {
            get {
                return ResourceManager.GetString("FindPlaceText", resourceCulture);
            }
        }
        
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        internal static string NoLastCodesText {
            get {
                return ResourceManager.GetString("NoLastCodesText", resourceCulture);
            }
        }
        
        internal static string SavedsText {
            get {
                return ResourceManager.GetString("SavedsText", resourceCulture);
            }
        }
        
        internal static string EnabledText {
            get {
                return ResourceManager.GetString("EnabledText", resourceCulture);
            }
        }
        
        internal static string PrefixText {
            get {
                return ResourceManager.GetString("PrefixText", resourceCulture);
            }
        }
        
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        internal static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        internal static string SavedBarcodesText {
            get {
                return ResourceManager.GetString("SavedBarcodesText", resourceCulture);
            }
        }
        
        internal static string ClearAllText {
            get {
                return ResourceManager.GetString("ClearAllText", resourceCulture);
            }
        }
        
        internal static string NoSavedCodesText {
            get {
                return ResourceManager.GetString("NoSavedCodesText", resourceCulture);
            }
        }
    }
}
