//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmSTools.Resources.Languages {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PmSTools.Resources.Languages.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string MainPage_MainPage_PmS_Main_Tools {
            get {
                return ResourceManager.GetString("MainPage_MainPage_PmS_Main_Tools", resourceCulture);
            }
        }

        internal static string NotAvailableYet {
            get {
                return ResourceManager.GetString("NotAvailableYet", resourceCulture);
            }
        }

        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }

        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }

        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }

        internal static string PrefixsText {
            get {
                return ResourceManager.GetString("PrefixsText", resourceCulture);
            }
        }

        internal static string SavedText {
            get {
                return ResourceManager.GetString("SavedText", resourceCulture);
            }
        }

        internal static string NoPrefixesText {
            get {
                return ResourceManager.GetString("NoPrefixesText", resourceCulture);
            }
        }

        internal static string LastCodesText {
            get {
                return ResourceManager.GetString("LastCodesText", resourceCulture);
            }
        }

        internal static string CameraText {
            get {
                return ResourceManager.GetString("CameraText", resourceCulture);
            }
        }

        internal static string FileText {
            get {
                return ResourceManager.GetString("FileText", resourceCulture);
            }
        }

        internal static string Code2BarcodeText {
            get {
                return ResourceManager.GetString("Code2BarcodeText", resourceCulture);
            }
        }

        internal static string FindPlaceText {
            get {
                return ResourceManager.GetString("FindPlaceText", resourceCulture);
            }
        }

        internal static string RouteCreationText {
            get {
                return ResourceManager.GetString("RouteCreationText", resourceCulture);
            }
        }

        internal static string RouteCreationPageTitleText {
            get {
                return ResourceManager.GetString("RouteCreationPageTitleText", resourceCulture);
            }
        }

        internal static string RouteCreationPageLabelText {
            get {
                return ResourceManager.GetString("RouteCreationPageLabelText", resourceCulture);
            }
        }

        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }

        internal static string NoLastCodesText {
            get {
                return ResourceManager.GetString("NoLastCodesText", resourceCulture);
            }
        }

        internal static string SavedsText {
            get {
                return ResourceManager.GetString("SavedsText", resourceCulture);
            }
        }

        internal static string EnabledText {
            get {
                return ResourceManager.GetString("EnabledText", resourceCulture);
            }
        }

        internal static string PrefixText {
            get {
                return ResourceManager.GetString("PrefixText", resourceCulture);
            }
        }

        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }

        internal static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }

        internal static string SavedBarcodesText {
            get {
                return ResourceManager.GetString("SavedBarcodesText", resourceCulture);
            }
        }

        internal static string ClearAllText {
            get {
                return ResourceManager.GetString("ClearAllText", resourceCulture);
            }
        }

        internal static string NoSavedCodesText {
            get {
                return ResourceManager.GetString("NoSavedCodesText", resourceCulture);
            }
        }

        internal static string AppTitleText {
            get {
                return ResourceManager.GetString("AppTitleText", resourceCulture);
            }
        }

        internal static string ShellMainTitleText {
            get {
                return ResourceManager.GetString("ShellMainTitleText", resourceCulture);
            }
        }

        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }

        internal static string CodeToBarcodeHintText {
            get {
                return ResourceManager.GetString("CodeToBarcodeHintText", resourceCulture);
            }
        }

        internal static string FindPlaceHintText {
            get {
                return ResourceManager.GetString("FindPlaceHintText", resourceCulture);
            }
        }

        internal static string CreateRoutesHintText {
            get {
                return ResourceManager.GetString("CreateRoutesHintText", resourceCulture);
            }
        }

        internal static string TakeCodeFromCameraHintText {
            get {
                return ResourceManager.GetString("TakeCodeFromCameraHintText", resourceCulture);
            }
        }

        internal static string TakeCodeFromFileHintText {
            get {
                return ResourceManager.GetString("TakeCodeFromFileHintText", resourceCulture);
            }
        }

        internal static string FindPlaceTitleText {
            get {
                return ResourceManager.GetString("FindPlaceTitleText", resourceCulture);
            }
        }

        internal static string LastSearchPlacesText {
            get {
                return ResourceManager.GetString("LastSearchPlacesText", resourceCulture);
            }
        }

        internal static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }

        internal static string TakeText {
            get {
                return ResourceManager.GetString("TakeText", resourceCulture);
            }
        }

        internal static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }

        internal static string TakeAddressFromCameraHintText {
            get {
                return ResourceManager.GetString("TakeAddressFromCameraHintText", resourceCulture);
            }
        }

        internal static string TakeAddressFromFileHintText {
            get {
                return ResourceManager.GetString("TakeAddressFromFileHintText", resourceCulture);
            }
        }

        internal static string CreateNewRouteText {
            get {
                return ResourceManager.GetString("CreateNewRouteText", resourceCulture);
            }
        }

        internal static string NoRoutesYetText {
            get {
                return ResourceManager.GetString("NoRoutesYetText", resourceCulture);
            }
        }

        internal static string RenameRouteDescriptionText {
            get {
                return ResourceManager.GetString("RenameRouteDescriptionText", resourceCulture);
            }
        }

        internal static string DeleteRouteDescriptionText {
            get {
                return ResourceManager.GetString("DeleteRouteDescriptionText", resourceCulture);
            }
        }

        internal static string MoveRouteUpDescriptionText {
            get {
                return ResourceManager.GetString("MoveRouteUpDescriptionText", resourceCulture);
            }
        }

        internal static string MoveRouteDownDescriptionText {
            get {
                return ResourceManager.GetString("MoveRouteDownDescriptionText", resourceCulture);
            }
        }

        internal static string DeleteAllRoutesText {
            get {
                return ResourceManager.GetString("DeleteAllRoutesText", resourceCulture);
            }
        }

        internal static string RenameRouteTitleText {
            get {
                return ResourceManager.GetString("RenameRouteTitleText", resourceCulture);
            }
        }

        internal static string RenameRoutePromptText {
            get {
                return ResourceManager.GetString("RenameRoutePromptText", resourceCulture);
            }
        }

        internal static string DeleteRouteTitleText {
            get {
                return ResourceManager.GetString("DeleteRouteTitleText", resourceCulture);
            }
        }

        internal static string DeleteRouteMessageFormatText {
            get {
                return ResourceManager.GetString("DeleteRouteMessageFormatText", resourceCulture);
            }
        }

        internal static string DeleteAllRoutesTitleText {
            get {
                return ResourceManager.GetString("DeleteAllRoutesTitleText", resourceCulture);
            }
        }

        internal static string DeleteAllRoutesMessageText {
            get {
                return ResourceManager.GetString("DeleteAllRoutesMessageText", resourceCulture);
            }
        }

        internal static string DeleteAllText {
            get {
                return ResourceManager.GetString("DeleteAllText", resourceCulture);
            }
        }

        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }

        internal static string RouteDisplayNameFormatText {
            get {
                return ResourceManager.GetString("RouteDisplayNameFormatText", resourceCulture);
            }
        }

        internal static string RouteDisplayNameWithNameFormatText {
            get {
                return ResourceManager.GetString("RouteDisplayNameWithNameFormatText", resourceCulture);
            }
        }

        internal static string RouteEditorTitleText {
            get {
                return ResourceManager.GetString("RouteEditorTitleText", resourceCulture);
            }
        }

        internal static string StartNearMeText {
            get {
                return ResourceManager.GetString("StartNearMeText", resourceCulture);
            }
        }

        internal static string OptimizeText {
            get {
                return ResourceManager.GetString("OptimizeText", resourceCulture);
            }
        }

        internal static string FullMapText {
            get {
                return ResourceManager.GetString("FullMapText", resourceCulture);
            }
        }

        internal static string NoStopsYetText {
            get {
                return ResourceManager.GetString("NoStopsYetText", resourceCulture);
            }
        }

        internal static string RouteMapText {
            get {
                return ResourceManager.GetString("RouteMapText", resourceCulture);
            }
        }

        internal static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }

        internal static string GeocodingText {
            get {
                return ResourceManager.GetString("GeocodingText", resourceCulture);
            }
        }

        internal static string OpenMapFullScreenHintText {
            get {
                return ResourceManager.GetString("OpenMapFullScreenHintText", resourceCulture);
            }
        }

        internal static string FirstText {
            get {
                return ResourceManager.GetString("FirstText", resourceCulture);
            }
        }

        internal static string LastText {
            get {
                return ResourceManager.GetString("LastText", resourceCulture);
            }
        }

        internal static string StopNumberFormatText {
            get {
                return ResourceManager.GetString("StopNumberFormatText", resourceCulture);
            }
        }

        internal static string StopOrderShortFormatText {
            get {
                return ResourceManager.GetString("StopOrderShortFormatText", resourceCulture);
            }
        }

        internal static string NamePlaceholderText {
            get {
                return ResourceManager.GetString("NamePlaceholderText", resourceCulture);
            }
        }

        internal static string StreetNamePlaceholderText {
            get {
                return ResourceManager.GetString("StreetNamePlaceholderText", resourceCulture);
            }
        }

        internal static string StreetNumberPlaceholderText {
            get {
                return ResourceManager.GetString("StreetNumberPlaceholderText", resourceCulture);
            }
        }

        internal static string PostalCodePlaceholderText {
            get {
                return ResourceManager.GetString("PostalCodePlaceholderText", resourceCulture);
            }
        }

        internal static string CityPlaceholderText {
            get {
                return ResourceManager.GetString("CityPlaceholderText", resourceCulture);
            }
        }

        internal static string CountryPlaceholderText {
            get {
                return ResourceManager.GetString("CountryPlaceholderText", resourceCulture);
            }
        }

        internal static string DeleteStopText {
            get {
                return ResourceManager.GetString("DeleteStopText", resourceCulture);
            }
        }

        internal static string NewStopManualText {
            get {
                return ResourceManager.GetString("NewStopManualText", resourceCulture);
            }
        }

        internal static string AddRouteStopText {
            get {
                return ResourceManager.GetString("AddRouteStopText", resourceCulture);
            }
        }

        internal static string RouteTitleFormatText {
            get {
                return ResourceManager.GetString("RouteTitleFormatText", resourceCulture);
            }
        }

        internal static string RouteTitleWithNameFormatText {
            get {
                return ResourceManager.GetString("RouteTitleWithNameFormatText", resourceCulture);
            }
        }

        internal static string RouteTitleWithStopFormatText {
            get {
                return ResourceManager.GetString("RouteTitleWithStopFormatText", resourceCulture);
            }
        }

        internal static string StopLabelPrefixText {
            get {
                return ResourceManager.GetString("StopLabelPrefixText", resourceCulture);
            }
        }

        internal static string MapSelectedLocationText {
            get {
                return ResourceManager.GetString("MapSelectedLocationText", resourceCulture);
            }
        }

        internal static string PlaceScanResultTitleText {
            get {
                return ResourceManager.GetString("PlaceScanResultTitleText", resourceCulture);
            }
        }

        internal static string PlaceDetailsText {
            get {
                return ResourceManager.GetString("PlaceDetailsText", resourceCulture);
            }
        }

        internal static string PlaceInformationText {
            get {
                return ResourceManager.GetString("PlaceInformationText", resourceCulture);
            }
        }

        internal static string EditFieldsText {
            get {
                return ResourceManager.GetString("EditFieldsText", resourceCulture);
            }
        }

        internal static string RepeatPhotoText {
            get {
                return ResourceManager.GetString("RepeatPhotoText", resourceCulture);
            }
        }

        internal static string ManualCorrectionText {
            get {
                return ResourceManager.GetString("ManualCorrectionText", resourceCulture);
            }
        }

        internal static string ApplyCorrectionsText {
            get {
                return ResourceManager.GetString("ApplyCorrectionsText", resourceCulture);
            }
        }

        internal static string LocationCandidatesText {
            get {
                return ResourceManager.GetString("LocationCandidatesText", resourceCulture);
            }
        }

        internal static string LocationMapText {
            get {
                return ResourceManager.GetString("LocationMapText", resourceCulture);
            }
        }

        internal static string LatitudeLabelText {
            get {
                return ResourceManager.GetString("LatitudeLabelText", resourceCulture);
            }
        }

        internal static string LongitudeLabelText {
            get {
                return ResourceManager.GetString("LongitudeLabelText", resourceCulture);
            }
        }

        internal static string HideEditorText {
            get {
                return ResourceManager.GetString("HideEditorText", resourceCulture);
            }
        }

        internal static string UnknownNameText {
            get {
                return ResourceManager.GetString("UnknownNameText", resourceCulture);
            }
        }

        internal static string UnknownStreetNameText {
            get {
                return ResourceManager.GetString("UnknownStreetNameText", resourceCulture);
            }
        }

        internal static string UnknownStreetNumberText {
            get {
                return ResourceManager.GetString("UnknownStreetNumberText", resourceCulture);
            }
        }

        internal static string UnknownPostalCodeText {
            get {
                return ResourceManager.GetString("UnknownPostalCodeText", resourceCulture);
            }
        }

        internal static string UnknownCityText {
            get {
                return ResourceManager.GetString("UnknownCityText", resourceCulture);
            }
        }

        internal static string UnknownCountryText {
            get {
                return ResourceManager.GetString("UnknownCountryText", resourceCulture);
            }
        }

        internal static string UnknownAddressText {
            get {
                return ResourceManager.GetString("UnknownAddressText", resourceCulture);
            }
        }

        internal static string NoLastPlaceInfoText {
            get {
                return ResourceManager.GetString("NoLastPlaceInfoText", resourceCulture);
            }
        }

        internal static string NoLastPlaceInfoAvailableText {
            get {
                return ResourceManager.GetString("NoLastPlaceInfoAvailableText", resourceCulture);
            }
        }

        internal static string NoDataTitleText {
            get {
                return ResourceManager.GetString("NoDataTitleText", resourceCulture);
            }
        }

        internal static string ClearHistoryTitleText {
            get {
                return ResourceManager.GetString("ClearHistoryTitleText", resourceCulture);
            }
        }

        internal static string DeleteSavedAddressHistoryText {
            get {
                return ResourceManager.GetString("DeleteSavedAddressHistoryText", resourceCulture);
            }
        }

        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }

        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }

        internal static string OpenText {
            get {
                return ResourceManager.GetString("OpenText", resourceCulture);
            }
        }

        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }

        internal static string OopsTitleText {
            get {
                return ResourceManager.GetString("OopsTitleText", resourceCulture);
            }
        }

        internal static string ErrorTitleText {
            get {
                return ResourceManager.GetString("ErrorTitleText", resourceCulture);
            }
        }

        internal static string NoSuccessTitleText {
            get {
                return ResourceManager.GetString("NoSuccessTitleText", resourceCulture);
            }
        }

        internal static string NoOcrPossibleText {
            get {
                return ResourceManager.GetString("NoOcrPossibleText", resourceCulture);
            }
        }

        internal static string ResultErrorTitleText {
            get {
                return ResourceManager.GetString("ResultErrorTitleText", resourceCulture);
            }
        }

        internal static string ResultIsNullText {
            get {
                return ResourceManager.GetString("ResultIsNullText", resourceCulture);
            }
        }

        internal static string MapCoordinatesAlertTitleText {
            get {
                return ResourceManager.GetString("MapCoordinatesAlertTitleText", resourceCulture);
            }
        }

        internal static string MapCoordinatesAlertMessageFormatText {
            get {
                return ResourceManager.GetString("MapCoordinatesAlertMessageFormatText", resourceCulture);
            }
        }

        internal static string NavigationTitleText {
            get {
                return ResourceManager.GetString("NavigationTitleText", resourceCulture);
            }
        }

        internal static string ReturnToPhotoCaptureErrorText {
            get {
                return ResourceManager.GetString("ReturnToPhotoCaptureErrorText", resourceCulture);
            }
        }

        internal static string ManualCorrectionsAppliedText {
            get {
                return ResourceManager.GetString("ManualCorrectionsAppliedText", resourceCulture);
            }
        }

        internal static string ManualCorrectionsApplyErrorText {
            get {
                return ResourceManager.GetString("ManualCorrectionsApplyErrorText", resourceCulture);
            }
        }

        internal static string SavedTitleText {
            get {
                return ResourceManager.GetString("SavedTitleText", resourceCulture);
            }
        }

        internal static string GeocodeDebugTitleText {
            get {
                return ResourceManager.GetString("GeocodeDebugTitleText", resourceCulture);
            }
        }

        internal static string GeocodeDebugNoCandidatesText {
            get {
                return ResourceManager.GetString("GeocodeDebugNoCandidatesText", resourceCulture);
            }
        }

        internal static string GeocodeDebugModeEnabledText {
            get {
                return ResourceManager.GetString("GeocodeDebugModeEnabledText", resourceCulture);
            }
        }

        internal static string GeocodeDebugParsedOcrText {
            get {
                return ResourceManager.GetString("GeocodeDebugParsedOcrText", resourceCulture);
            }
        }

        internal static string GeocodeDebugNameLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugNameLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugStreetLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugStreetLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugStreetNameLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugStreetNameLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugStreetNumberLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugStreetNumberLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugParsedStreetNumberLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugParsedStreetNumberLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugDesiredHouseNumberLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugDesiredHouseNumberLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugPostalCodeLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugPostalCodeLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugCityLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugCityLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugCountryLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugCountryLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugCandidatesLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugCandidatesLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugReasonLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugReasonLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugTopSpainQueriesText {
            get {
                return ResourceManager.GetString("GeocodeDebugTopSpainQueriesText", resourceCulture);
            }
        }

        internal static string GeocodeDebugTopGlobalQueriesText {
            get {
                return ResourceManager.GetString("GeocodeDebugTopGlobalQueriesText", resourceCulture);
            }
        }

        internal static string GeocodeDebugTopCandidatesText {
            get {
                return ResourceManager.GetString("GeocodeDebugTopCandidatesText", resourceCulture);
            }
        }

        internal static string GeocodeDebugHouseNumberLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugHouseNumberLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugTypeLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugTypeLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugMatchLabelText {
            get {
                return ResourceManager.GetString("GeocodeDebugMatchLabelText", resourceCulture);
            }
        }

        internal static string GeocodeDebugNoneText {
            get {
                return ResourceManager.GetString("GeocodeDebugNoneText", resourceCulture);
            }
        }

        internal static string GeocodeDebugEmptyText {
            get {
                return ResourceManager.GetString("GeocodeDebugEmptyText", resourceCulture);
            }
        }

        internal static string MapMarkerDefaultLabelText {
            get {
                return ResourceManager.GetString("MapMarkerDefaultLabelText", resourceCulture);
            }
        }

        internal static string ExactNumberMatchBadgeText {
            get {
                return ResourceManager.GetString("ExactNumberMatchBadgeText", resourceCulture);
            }
        }

        internal static string DefaultCountryText {
            get {
                return ResourceManager.GetString("DefaultCountryText", resourceCulture);
            }
        }

        internal static string BarcodePopupTitleText {
            get {
                return ResourceManager.GetString("BarcodePopupTitleText", resourceCulture);
            }
        }

        internal static string AboutTitleText {
            get {
                return ResourceManager.GetString("AboutTitleText", resourceCulture);
            }
        }

        internal static string AboutMadeByText {
            get {
                return ResourceManager.GetString("AboutMadeByText", resourceCulture);
            }
        }

        internal static string AboutForStudioText {
            get {
                return ResourceManager.GetString("AboutForStudioText", resourceCulture);
            }
        }

        internal static string AboutCopyrightText {
            get {
                return ResourceManager.GetString("AboutCopyrightText", resourceCulture);
            }
        }

        internal static string RemoveSymbolText {
            get {
                return ResourceManager.GetString("RemoveSymbolText", resourceCulture);
            }
        }

        internal static string PrefixPlaceholderText {
            get {
                return ResourceManager.GetString("PrefixPlaceholderText", resourceCulture);
            }
        }

        internal static string FullScreenMapTitleText {
            get {
                return ResourceManager.GetString("FullScreenMapTitleText", resourceCulture);
            }
        }

        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }

        internal static string MapNotAvailableText {
            get {
                return ResourceManager.GetString("MapNotAvailableText", resourceCulture);
            }
        }

        internal static string NoPrefixFoundText {
            get {
                return ResourceManager.GetString("NoPrefixFoundText", resourceCulture);
            }
        }

        internal static string PrefixesCountEmptyText {
            get {
                return ResourceManager.GetString("PrefixesCountEmptyText", resourceCulture);
            }
        }

        internal static string PrefixesLabelFormatText {
            get {
                return ResourceManager.GetString("PrefixesLabelFormatText", resourceCulture);
            }
        }

        internal static string OptimizeRouteTitleText {
            get {
                return ResourceManager.GetString("OptimizeRouteTitleText", resourceCulture);
            }
        }

        internal static string OptimizeNeedTwoStopsText {
            get {
                return ResourceManager.GetString("OptimizeNeedTwoStopsText", resourceCulture);
            }
        }

        internal static string OptimizeNotEnoughStopsWithCoordsText {
            get {
                return ResourceManager.GetString("OptimizeNotEnoughStopsWithCoordsText", resourceCulture);
            }
        }

        internal static string SomeStopsCouldNotBeGeocodedText {
            get {
                return ResourceManager.GetString("SomeStopsCouldNotBeGeocodedText", resourceCulture);
            }
        }

        internal static string OptimizeNoLocationText {
            get {
                return ResourceManager.GetString("OptimizeNoLocationText", resourceCulture);
            }
        }

        internal static string StartNearMeNeedTwoStopsText {
            get {
                return ResourceManager.GetString("StartNearMeNeedTwoStopsText", resourceCulture);
            }
        }

        internal static string StartNearMeNoLocationText {
            get {
                return ResourceManager.GetString("StartNearMeNoLocationText", resourceCulture);
            }
        }

        internal static string StartNearMeNoStopsWithCoordsText {
            get {
                return ResourceManager.GetString("StartNearMeNoStopsWithCoordsText", resourceCulture);
            }
        }

        internal static string StartNearMeNearestStopErrorText {
            get {
                return ResourceManager.GetString("StartNearMeNearestStopErrorText", resourceCulture);
            }
        }

    }
}
